// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bohfghebvortwlnmlhfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvaGZnaGVidm9ydHdsbm1saGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzYyODQsImV4cCI6MjA2MDA1MjI4NH0.I-EgsYAUAl37sjbzG8oqIvXO1WP9RjkZ7qJzJ5In6P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);